<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubConfigurationsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sub_configurations')->insert([
            [
                'id' => 3,
                'code' => 'COGS-02',
                'name' => 'average',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'code' => 'COGS-03',
                'name' => 'LIFO',
                'types' => 'non-mandatory',
                'status' => 0,
                'value' => null,
                'configurations_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'code' => 'INV-T-01',
                'name' => 'perpetual',
                'types' => 'mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'code' => 'INV-T-02',
                'name' => 'periodic',
                'types' => 'non-mandatory',
                'status' => 0,
                'value' => null,
                'configurations_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'code' => 'S-PAY-01',
                'name' => 'cash',
                'types' => 'mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'code' => 'S-PAY-02',
                'name' => 'transfer',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'code' => 'S-PAY-03',
                'name' => 'qris',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'code' => 'DISC-01',
                'name' => 'diskon produk tertentu',
                'types' => 'non-mandatory',
                'status' => 0,
                'value' => 0,
                'configurations_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'code' => 'DISC-02',
                'name' => 'global',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => 5,
                'configurations_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'code' => 'DISC-03',
                'name' => 'cashback',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => 5,
                'configurations_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'code' => 'DEL-01',
                'name' => 'barang diambil pembeli',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'code' => 'DEL-02',
                'name' => 'barang diantar ke pembeli',
                'types' => 'mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'code' => 'RE-01',
                'name' => 'barang diambil ke supplier',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 7,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'code' => 'RE-02',
                'name' => 'barang diantar suppplier',
                'types' => 'mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 7,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'code' => 'P-PAY-01',
                'name' => 'cash',
                'types' => 'mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 6,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'code' => 'P-PAY-02',
                'name' => 'transfer',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 6,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'code' => 'P-PAY-03',
                'name' => 'hutang',
                'types' => 'non-mandatory',
                'status' => 1,
                'value' => null,
                'configurations_id' => 6,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
